### PR TITLE
modify portalSearchIndexBaseUrl

### PR DESCRIPTION
**Pull request by danfruehauf**

### CODE REVIEW

**Comment by jkburges** [comment]
I _think_ this PR is incorrect, based on what is currently deployed at https://imos.aodn.org.au/data_collections.html (each data collection is located at a URL such as https://imos.aodn.org.au/<collection_name>.html).  i.e. there is no "data_collections" in the path.  Agree?

**Comment by danfruehauf** [comment]
Not from what I understood. The whole thing should be under `data_collections`. If we don't create that extra safe hierarchy, then it may or may not collide with portal on the same domain name.

**Comment by jkburges** [comment]
I agree it'd be a good idea to have that extra level of hierarchy but should we check this is what @pblain wants (in case it's a SEO requirement?)

**Comment by danfruehauf** [comment]
I see the current links.

Well, I don't mind keeping it that way, but it's rather dangerous.

**Comment by danfruehauf** [comment]
That PR is indeed wrong.

**Comment by jkburges** [comment]
Why, out of interest?

**Comment by danfruehauf** [comment]
Having a static page of `imos123` in that directory will (I think) override access to the webapp (the `ProxyPass` directives). Besides, it's a bit cleaner, having everything under one context.

**Pull request closed without merging**
